apiVersion: autoscaling.cast.ai/v1
kind: Recommendation
metadata:
  name: budgeted-workload-safe
  namespace: woop-guardrail-poc
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: budgeted-workload
  recommendation:
    - containerName: main
      requests:
        cpu: "8"
        memory: 40Gi
    - containerName: sidecar
      requests:
        cpu: 1500m
        memory: 2Gi
